language: go

go:
  - 1.8.x

os: osx

script: 
  - go get github.com/divanvisagie/ui
  - go get cloud.google.com/go/translate
  - go build
 
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash